# ENUM
# AUTORES: JHONEYKER DELGADO, EMMANUEL VALENCIA, SIMON GUARIN, CAMILO MIRANDA Y JACOBO LEAL.

from enum import Enum

class Ubicacion(Enum):

    PASILLO = 'PASILLO'
    VENTANA = 'VENTANA'
    CENTRAL = 'CENTRAL'

